### ISSUE TITLE
Investigate: Atlas is not showing person counts for the non-standard codes

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/ETL#126]
Atlas in sandbox is not showing person counts for the non-standard codes
![image](https://github.com/FINNGEN/ETL/assets/54809193/510693c6-e48c-4be9-8caf-a87a7c8aecbb)

atlas demo ohsdi does
![image](https://github.com/FINNGEN/ETL/assets/54809193/77f07cd4-063d-4cbe-b67a-b1fad7c82445)

**Comment by shanmukhasampath** [comment]
Updating the achilles tables (achilles_analysis, achilles_results and achilles_result_concept_count) is not enough but the `webapi.cdm_cache` should be cleared out to make these updates work. 

The discussion regarding this cache clean is here
https://forums.ohdsi.org/t/how-to-force-the-update-of-reports-in-atlas/14282

The solution is in this Atlas git issue
https://github.com/OHDSI/Atlas/issues/447#issuecomment-1768347614
