### ISSUE TITLE
update sql tables as per data freeze 12

### ISSUE THREAD

**Issue by shanmukhasampath** [FINNGEN/ETL#158]
DF12 SQL fixes

- [x] Setting up environment - minimum_extended table has column with changed names. Update to account these changes.
- [x] Visit Occurrence - `SOURCE ` **BIOBANK** needs to make the change to include missing `BL_AGE`
- [x] BIRTH_MOTHER stem - Birth mother now have `APPROX_DELIVERY_DATE` column which conflicts with calculated `APPROX_DELIVERY_DATE`
- [x] cdm source - Change it to DF12
- [x] Update `export_tables.sh` to change the storage bucket
- [x] Update `config_template.yml` to account for DF12 changes

**Comment by javier-gracia-tabuenca-tuni** [comment]
is this completed ?

**Comment by shanmukhasampath** [comment]
Hi @javier-gracia-tabuenca-tuni, yes this is completed.
