### ISSUE TITLE
Update birth mother registry ETL for DF12

### ISSUE THREAD

**Issue by shanmukhasampath** [FINNGEN/ETL#162]
In DF11 release, birth mother registry data had different delivery dates for twins, triplets and more which was captured in the column `APPROX_BIRTH_DATE.` This is mainly due to the fact that register team was adding offset to `APPROX_BIRTH_DATE` to mask the original date randomly. To bypass this, we used finngenid birthday + mother's birth event age. 

In DF12, this problem is fixed by introducing `APPROX_DELIVERY_DATE` which now shows same day or a difference in a day for twins, triplets and more other birth types. Given this, the birth mother stem medical events SQL should be updated to capture this information.

- [x] Use `APPROX_DELIVERY_DATE` instead of using finngenid birthday + mother's birth event age
- [x] Properly address twin or more births. **NO NEED FOR THIS**
- [x] Create unit tests for delivery date and identification. 
- [ ] https://github.com/FINNGEN/ETL/issues/184

**Comment by javier-gracia-tabuenca-tuni** [comment]
is this completed ?

**Comment by shanmukhasampath** [comment]
Hi @javier-gracia-tabuenca-tuni, no it is finished. 
1. `APPROX_DELIVERY_DATE` is done but needs testing. 
2. Twin births might be scrapped because there are only two instances where twins is not properly addressed the rest of them have correct codes for twin births which we already took care of. I checked this before I went for holidays.
