### ISSUE TITLE
Drug Exposure table will have both VNR and ATC codes

### ISSUE THREAD

**Issue by shanmukhasampath** [FINNGEN/ETL#163]
The current `drug_exposure` table only has VNR code in the `drug_source_value` but does not contain ATC code as both TVT and Atlas users want to use ATC code to get record count or filter. The remedy is to duplicate drug exposure row with ATC code as `drug_source_value` along with relevant concept_id of the ATC code.

Steps to do:

- [ ] `etl_drug_exposure.sql` will have duplicate row with ATC code in `drug_source_value` along with `drug_source_concept_id`
- [ ] Add unit test to check for ATC code as well
- [ ] `etl_drug_era.sql` will need to be checked so that the era calculations are not disturbed.
- [ ] Test this out in dockerized Atlas if record counts are visible for ATC codes

**Comment by javier-gracia-tabuenca-tuni** [comment]
I think this is a bad idea

we should use the ATC calsification instead
